server:
  port: 8080

spring:
  liquibase:
    default-schema: currency_exchange
    change-log: classpath:db/changelog_init.xml
    enabled: true
    drop-first: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: skillbox
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        hbm2ddl:
          auto: none
        default_schema: currency_exchange

currency-resourse: ${FILE_RESOURCE:classpath:.\src\main\resources\cbr-xml-daily.ru_daily_utf8.xml}

